name: CI/CD Impacta
run-name: "Action iniciada por @${{ github.actor }} na branch ${{github.ref_name}}"

on:
  push:
    branches: ["dev"]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:

env:
  FILE_NAME: ${{vars.FILE_NAME}}

jobs:
  download-and-run-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Step: Cloning repository..."
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: ./.github/actions/build_go
        with:
          vars: ${{env.FILE_NAME}}

      - name: "Upload Artifact..."
        uses: ./.github/actions/artifactUpload
        with:
          vars: ${{env.FILE_NAME}}

  download-only-windows:
    runs-on: windows-latest
    steps:
      - name: "Step: Cloning repository..."
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: ./.github/actions/build_go
        with:
          vars: ${{env.FILE_NAME}}

      - name: "Upload Artifact..."
        uses: ./.github/actions/artifactUpload
        with:
          vars: ${{env.FILE_NAME}}